chore: updating dependabot to support gha, python, docker and dev container packages
rajpalc7/aries-cloudagent-python pull request #1
Opened 2024-05-02 19:59 UTC by rajpalc7

2024-05-02 20:20 UTC, rajpalc7 commented
Hi @WadeBarnes , this is ready for review now.

2024-05-06 13:44 UTC, WadeBarnes requested changes
@rajpalc7, You are missing a number of Docker files.

2024-05-06 16:37 UTC, rajpalc7 commented
Hi @WadeBarnes,  other Docker files are added now.

2024-05-06 19:22 UTC, WadeBarnes approved these changes

2024-05-16 21:09 UTC, closed without merging